title: Default Response
description: Activity list with one daily and one one-time activity
code: 200
response: |
    {
        "message": "SUCCESS",
        "activities": [
            {
                "activityId": "health-history",
                "activityVersion": "1.1",
                "title": "Medical History",
                "type": "questionnaire",
                "startTime": "2024-01-01T07:00:00.000+0000",
                "endTime": "2026-01-29T23:59:59.000+0000",
                "branching": false,
                "isLaunchStudy": false,
                "isStudyLifeTime": false,
                "lastModified": "2024-01-01T10:23:29.000+0000",
                "state": "active",
                "taskSubType": "",
                "schedulingType": "Regular",
                "anchorDate": {
                    "sourceType": "",
                    "sourceActivityId": "",
                    "sourceKey": "",
                    "sourceFormKey": "",
                    "start": {
                        "anchorDays": 0,
                        "dayOfWeek": 0,
                        "dateOfMonth": "",
                        "time": ""
                    },
                    "end": {
                        "anchorDays": 0,
                        "repeatInterval": 0,
                        "time": ""
                    }
                },
                "frequency": {
                    "type": "One time",
                    "runs": [
                        {
                            "startTime": "07:00:00",
                            "endTime": "23:59:59"
                        }
                    ],
                    "anchorRuns": []
                }
            },
            {
                "activityId": "demographic-info",
                "activityVersion": "1.1",
                "title": "Demographic Info",
                "type": "questionnaire",
                "startTime": "2024-01-01T07:00:00.000+0000",
                "endTime": "2026-01-29T23:59:59.000+0000",
                "branching": false,
                "isLaunchStudy": false,
                "isStudyLifeTime": false,
                "lastModified": "2024-01-01T10:23:29.000+0000",
                "state": "active",
                "taskSubType": "",
                "schedulingType": "Regular",
                "anchorDate": {
                    "sourceType": "",
                    "sourceActivityId": "",
                    "sourceKey": "",
                    "sourceFormKey": "",
                    "start": {
                        "anchorDays": 0,
                        "dayOfWeek": 0,
                        "dateOfMonth": "",
                        "time": ""
                    },
                    "end": {
                        "anchorDays": 0,
                        "repeatInterval": 0,
                        "time": ""
                    }
                },
                "frequency": {
                    "type": "One time",
                    "runs": [
                        {
                            "startTime": "07:00:00",
                            "endTime": "23:59:59"
                        }
                    ],
                    "anchorRuns": []
                }
            }
        ]
    }
