title: Default Response
description: Response with eligibility token, eligibility test and comprehension test.
code: 200
response: |
  {
      "message": "SUCCESS",
      "eligibility": {
          "type": "combined",
          "tokenTitle": "Participating in this study requires an invitation. If you have received one, please enter the token provided.",
          "test": [
              {
                  "type": "Question",
                  "resultType": "boolean",
                  "key": "eligibility-lang",
                  "title": "Are you able to provide consent in English?",
                  "text": "Answer these questions to determine your eligibility for the study",
                  "skippable": false,
                  "repeatable": false
              },
              {
                  "type": "Question",
                  "resultType": "boolean",
                  "key": "loc",
                  "title": "Are you located in Accra?",
                  "text": "Answer these questions to determine your eligibility for the study",
                  "skippable": false,
                  "repeatable": false
              },
              {
                  "type": "Question",
                  "resultType": "boolean",
                  "key": "adult",
                  "title": "Are you 18 years of age or greater?",
                  "text": "Answer these questions to determine your eligibility for the study",
                  "skippable": false,
                  "repeatable": false
              },
              {
                  "type": "Question",
                  "resultType": "boolean",
                  "key": "pregnant",
                  "title": "Are you pregnant?",
                  "text": "Answer these questions to determine your eligibility for the study",
                  "skippable": false,
                  "repeatable": false
              },
              {
                  "type": "Question",
                  "resultType": "boolean",
                  "key": "15weeks",
                  "title": "Are you past 15 weeks of pregnancy?",
                  "text": "Answer these questions to determine your eligibility for the study",
                  "skippable": false,
                  "repeatable": false
              },
              {
                  "type": "Question",
                  "resultType": "boolean",
                  "key": "fitbit",
                  "title": "Are you comfortable with wearing and using the provided Fitbit activity tracker?",
                  "text": "Answer these questions to determine your eligibility for the study",
                  "skippable": false,
                  "repeatable": false
              },
              {
                  "type": "Question",
                  "resultType": "boolean",
                  "key": "visit",
                  "title": "Are you able to attend prenatal and postnatal visits at the University of Ghana Medical Center (UGMC)?",
                  "text": "Answer these questions to determine your eligibility for the study",
                  "skippable": false,
                  "repeatable": false
              }
          ],
          "correctAnswers": [
              {
                  "answer": true,
                  "key": "eligibility-lang"
              },
              {
                  "answer": true,
                  "key": "loc"
              },
              {
                  "answer": true,
                  "key": "adult"
              },
              {
                  "answer": true,
                  "key": "pregnant"
              },
              {
                  "answer": false,
                  "key": "15weeks"
              },
              {
                  "answer": true,
                  "key": "fitbit"
              },
              {
                  "answer": true,
                  "key": "visit"
              }
          ]
      },
      "consent": {
          "version": "1.1",
          "visualScreens": [
              {
                  "type": "overview",
                  "title": "Review this information and consent to participate in this study",
                  "text": "This consent form gives you important information about a research study.",
                  "html": "We are asking you to participate in this research study. Participation in this research study is voluntary.",
                  "visualStep": true
              }
          ],
          "sharing" : {
            "longDesc" : "Share my data with UGMC and qualified researchers worldwide.",
            "shortDesc" : "Only Share my data with UGMC and partners",
            "title" : "Sharing Options",
            "learnMore" : "",
            "allowWithoutSharing" : false,
            "text" : "The host and its partners will receive your study data from participation in this study. Sharing your coded data more broadly (without information such as your name) may benefit this and future research."
          },
          "comprehension": {
              "passScore": 2,
              "questions": [
                  {
                      "type": "Question",
                      "resultType": "textChoice",
                      "key": "123",
                      "title": "I can choose not to participate in the study at any time.",
                      "text": "Take this comprehension test to assess your understanding of the study",
                      "skippable": false,
                      "repeatable": false,
                      "destinations": [],
                      "format": {
                          "textChoices": [
                              {
                                  "text": "Yes",
                                  "value": "Yes",
                                  "exclusive": false
                              },
                              {
                                  "text": "No",
                                  "value": "No",
                                  "exclusive": false
                              }
                          ],
                          "selectionStyle": "Multiple"
                      }
                  },
                  {
                      "type": "Question",
                      "resultType": "textChoice",
                      "key": "234",
                      "title": "Which are all the statements that represent the objectives of the study?",
                      "text": "Take this comprehension test to assess your understanding of the study",
                      "skippable": false,
                      "repeatable": false,
                      "destinations": [],
                      "format": {
                          "textChoices": [
                              {
                                  "text": "Understand how physiological metrics may change during pregnancy.",
                                  "value": "1",
                                  "exclusive": false
                              },
                              {
                                  "text": "Determine whether physiological changes can be leveraged by machine learning algorithms to detect or predict pregnancy outcomes.",
                                  "value": "2",
                                  "exclusive": false
                              },
                              {
                                  "text": "Understand the correlation between diet and stress.",
                                  "value": "3",
                                  "exclusive": false
                              },
                              {
                                  "text": "Determine whether wearable devices enable behavioural changes which may improve pregnancy outcomes.",
                                  "value": "4",
                                  "exclusive": false
                              }
                          ],
                          "selectionStyle": "Multiple"
                      }
                  }
              ],
              "correctAnswers": [
                  {
                      "key": "123",
                      "answer": [
                          "Yes"
                      ],
                      "evaluation": "all"
                  },
                  {
                      "key": "234",
                      "answer": [
                          "1",
                          "2",
                          "4"
                      ],
                      "evaluation": "all"
                  }
              ]
          }
      }
  }
