title: Default Response
description: Response with Sample Study Info
code: 200
response: |
  {
      "message": "SUCCESS",
      "info": [
          {
              "type": "image",
              "image": "https://images.unsplash.com/photo-1529310399831-ed472b81d589?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=774&q=80",
              "title": "Akuaba Maternal Health Study",
              "text": "The focus of this study is to understand the feasibility of wearables and mobile-health based longitudinal surveys for maternal health in Ghana."
          }
      ]
  }
