name: fda_mystudies_http_client
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.1.0
  get_it: ^7.2.0
  http: ^1.1.0
  fda_mystudies_spec:
    path: "../fda_mystudies_spec"
  uuid: ^4.0.0
  yaml: ^3.1.0
  path: ^1.8.0
  crypto: ^3.0.3
  sqflite:
  fitbitter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  injectable_generator: ^2.1.4
  build_runner: ^2.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/mock/scenario/
    - assets/mock/scenario/authentication_service/login/
    - assets/mock/scenario/authentication_service/sign_in/
    - assets/mock/scenario/authentication_service/change_password/
    - assets/mock/scenario/authentication_service/grant_verified_user/
    - assets/mock/scenario/authentication_service/logout/
    - assets/mock/scenario/authentication_service/reset_password/
    - assets/mock/scenario/common/
    - assets/mock/scenario/participant_consent_datastore_service/consent_document/
    - assets/mock/scenario/participant_consent_datastore_service/update_eligibility_consent_status/
    - assets/mock/scenario/participant_enroll_datastore_service/enroll/
    - assets/mock/scenario/participant_enroll_datastore_service/study_state/
    - assets/mock/scenario/participant_enroll_datastore_service/update_study_state/
    - assets/mock/scenario/participant_enroll_datastore_service/validate_enrollment_token/
    - assets/mock/scenario/participant_enroll_datastore_service/withdraw_from_study/
    - assets/mock/scenario/participant_user_datastore_service/app_info/
    - assets/mock/scenario/participant_user_datastore_service/contact_us/
    - assets/mock/scenario/participant_user_datastore_service/deactivate/
    - assets/mock/scenario/participant_user_datastore_service/feedback/
    - assets/mock/scenario/participant_user_datastore_service/register/
    - assets/mock/scenario/participant_user_datastore_service/resend_confirmation/
    - assets/mock/scenario/participant_user_datastore_service/update_user_profile/
    - assets/mock/scenario/participant_user_datastore_service/user_profile/
    - assets/mock/scenario/participant_user_datastore_service/verify_email/
    - assets/mock/scenario/response_datastore_service/activity_state/
    - assets/mock/scenario/response_datastore_service/process_response/
    - assets/mock/scenario/response_datastore_service/update_activity_state/
    - assets/mock/scenario/study_datastore_service/activity_list/
    - assets/mock/scenario/study_datastore_service/activity_steps/
    - assets/mock/scenario/study_datastore_service/consent_document/
    - assets/mock/scenario/study_datastore_service/eligibility_and_consent/
    - assets/mock/scenario/study_datastore_service/study_dashboard/
    - assets/mock/scenario/study_datastore_service/study_info/
    - assets/mock/scenario/study_datastore_service/study_list/
    - assets/mock/scenario/study_datastore_service/version_info/
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
