title: Get acitvity state success response
description: Response with test activity
code: 200
response: |
  {
    "message": "success",
    "activities": [
        {
            "activityId": "health-history",
            "activityRun": {
              "completed": 0,
              "missed": 0,
              "total": 1
            },
            "activityRunId": "1",
            "activityState": "yetToJoin",
            "activityVersion": "1.1"
        },
        {
            "activityId": "demographic-info",
            "activityRun": {
              "completed": 0,
              "missed": 0,
              "total": 1
            },
            "activityRunId": "1",
            "activityState": "yetToJoin",
            "activityVersion": "1.1"
        }
    ]
  }
